# This workflow will install Python dependencies and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint


on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Flake8 Annotator
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. Use 90 characters per line as the limit for Python code.
        flake8 . --count --exit-zero --ignore=F403,F405 --max-complexity=10 --max-line-length=90 --statistics

